name = "BrainVisionDataFormat"
uuid = "a1c37e40-cd17-11e8-241b-47481c954d92"
authors = ["igmmgi <ian.mackenzie@uni-tuebingen.de>"]
version = "0.1.0"
license = "MIT"

[deps]

[compat]
julia = "1.10"

[extras]
Documenter = "e30172f5-a6a5-5a46-863b-614d45cd2de4"
DocumenterTools = "35a29f4d-8980-5a13-9543-d66fff28ecb8"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
docs = ["Documenter", "DocumenterTools"]
